Repository imhardikdesai/Quiz-App, pull requests merged in 2023-10, with the labels that each got.

#4 Update index.css
  src/index.css
Labels: hacktoberfest-accepted, hacktoberfest

#5 Update index.js
  src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#9 Update QuestionBox.css
  src/components/QuestionBox/QuestionBox.css
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#14 Improved Navbar and Readability of about page
  package-lock.json
  package.json
  src/components/NavBar/NavBar.jsx
  src/pages/About/About.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#15 scoreboard css is modified plz check if its fine
  src/components/NavBar/NavBar.jsx
  src/pages/ScoreBoard/Scoreboard.css
  src/pages/ScoreBoard/Scoreboard.jsx
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest
